services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      USER_SERVICE_URL: http://user-service:5001
      PRODUCT_ORDER_SERVICE_URL: http://product-order-service:5002
    depends_on:
      - user-service
      - product-order-service
    networks:
      - micronet

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@user-db:5432/userdb
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - micronet

  user-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - micronet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 10s
      timeout: 3s
      retries: 20

  product-order-service:
    build: ./product-order-service
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: postgresql+psycopg2://order_food:pass@product-order-db:5432/orderfooddb
      USER_SERVICE_URL: http://user-service:5001
    depends_on:
      product-order-db:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - micronet

  product-order-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: orderfooddb
      POSTGRES_USER: order_food
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - product_order_data:/var/lib/postgresql/data
    networks:
      - micronet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_food -d orderfooddb"]
      interval: 10s
      timeout: 3s
      retries: 20

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      API_GATEWAY_URL: http://api-gateway:5000
      SECRET_KEY: foodnow-secret-key-2024
    depends_on:
      - api-gateway
    volumes:
      - ./frontend/static/images/foods:/app/static/images/foods
    networks:
      - micronet

volumes:
  user_data:
  product_order_data:

networks:
  micronet:
    driver: bridge
